export const GET_USER_COORDS_BEGIN = "GET_USER_COORDS_BEGIN";
export const GET_USER_COORDS_SUCCESS = "GET_USER_COORDS_SUCCESS";
export const GET_USER_COORDS_FAILURE = "GET_USER_COORDS_FAILURE";

export const FETCH_OPEN_WEATHER_BEGIN = "FETCH_OPEN_WEATHER_BEGIN";
export const FETCH_OPEN_WEATHER_SUCCESS = "FETCH_OPEN_WEATHER_SUCCESS";
export const FETCH_OPEN_WEATHER_FAILURE = "FETCH_OPEN_WEATHER_FAILURE";

export const FETCH_WEATHER_STACK_BEGIN = "FETCH_WEATHER_STACK_BEGIN";
export const FETCH_WEATHER_STACK_SUCCESS = "FETCH_WEATHER_STACK_SUCCESS";
export const FETCH_WEATHER_STACK_FAILURE = "FETCH_WEATHER_STACK_FAILURE";
