export const GET_USER_COORDS_BEGIN = "GET_USER_COORDS_BEGIN";
export const GET_USER_COORDS_SUCCESS = "GET_USER_COORDS_SUCCESS";
export const GET_USER_COORDS_FAILURE = "GET_USER_COORDS_FAILURE";

export const FETCH_OPEN_WEATHER_BEGIN = "FETCH_OPEN_WEATHER_BEGIN";
export const FETCH_OPEN_WEATHER_SUCCESS = "FETCH_OPEN_WEATHER_SUCCESS";
export const FETCH_OPEN_WEATHER_FAILURE = "FETCH_OPEN_WEATHER_FAILURE";

export const FETCH_WEATHER_API_BEGIN = "FETCH_WEATHER_API_BEGIN";
export const FETCH_WEATHER_API_SUCCESS = "FETCH_WEATHER_API_SUCCESS";
export const FETCH_WEATHER_API_FAILURE = "FETCH_WEATHER_API_FAILURE";
